CREATE TABLE S(
	SNO VARCHAR(10) PRIMARY KEY,
	SNAME VARCHAR(100),
	STATUS INT(10),
	CITY VARCHAR(50)
);

CREATE TABLE P(
	PNO VARCHAR(10) PRIMARY KEY,
	PNAME VARCHAR(100),
	COLOR VARCHAR(10),
	WEIGHT INT(10)
);

CREATE TABLE J(
	JNO VARCHAR(10) PRIMARY KEY,
	JNAME VARCHAR(100),
	CITY VARCHAR(100)
);

CREATE TABLE SPJ(
	SNO VARCHAR(10) PRIMARY KEY,
	PNO VARCHAR(10) PRIMARY KEY,
	JNO VARCHAR(10) PRIMARY KEY,
	QTY INT(10)
);